### ISSUE TITLE
Getting symbol of Reference Of Array[] Of Struct element exception

### ISSUE THREAD

**Issue by sjelatex** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#63]
When using the TwinCAT.Ads NuGet package version 4.4.37 (or 4.4.26), attempting to access the symbolic information of a specific index of a 'REFERENCE TO ARRAY[...] OF STRUCT' using the AdsSymbolLoader causes an exception:
```
System.InvalidCastException: 'Unable to cast object of type 'TwinCAT.Ads.TypeSystem.StructInstance' to type 'TwinCAT.TypeSystem.IArrayInstance'.'
```
with the stack trace
```
   at TwinCAT.Ads.TypeSystem.ReferenceInstance.TwinCAT.TypeSystem.IReferenceInstanceAccess.TryGetElement(IList`1 jaggedIndices, ISymbol& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetSubItem(IInstanceCollection`1 coll, String[] pathSplit, Int32 splitIndex, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetSubItem(IInstanceCollection`1 coll, String[] pathSplit, Int32 splitIndex, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetInstanceHierarchically(String instancePath, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetInstance(String instanceSpecifier, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.get_Item(String instanceSpecifier)
   at TwinCAT.TypeSystem.Generic.ReadOnlyInstanceCollection`1.get_Item(String instancePath)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\User\Desktop\Sample\ConsoleApp13\ConsoleApp13\Program.cs:line 44
```
The issue does not occur with TwinCAT.Ads NuGet package version 6.1.316.

Below is a minimal example showing four ways of accessing the symbol of a specific index of arrays but only the last throws the exception.
```csharp
using (TcAdsClient client = new TcAdsClient())
{
    client.Connect(AmsNetId.Local, 851);
    var loader = SymbolLoaderFactory.Create(client, SymbolLoaderSettings.Default);
    var symbols = loader.Symbols;

    var instancePath = "MAIN.MyArray";
    var symbol = symbols[instancePath];
    var subSymbol = symbol.SubSymbols[0]; // Works

    var instancePath2 = "MAIN.MyArray[1]";
    var symbol2 = symbols[instancePath2]; // Works

    var instancePath3 = "MAIN.RefArray";
    var symbol3 = symbols[instancePath3];
    var subSymbol3 = symbol3.SubSymbols[0]; // Works

    var instancePath4 = "MAIN.RefArray[1]";
    var symbol4 = symbols[instancePath4]; // Throws the exception below
    // System.InvalidCastException: 'Unable to cast object of type 'TwinCAT.Ads.TypeSystem.StructInstance' to type 'TwinCAT.TypeSystem.IArrayInstance'.'
}
```
Where in the TwinCAT, the project has been defined as
```
PROGRAM MAIN
VAR
    MyArray: ARRAY[1..2] OF Test;
    RefArray: REFERENCE TO ARRAY[1..2] OF TEST;
END_VAR
-----------------
RefArray REF= MyArray;
-----------------
TYPE Test :
STRUCT
    Number : INT;
    Text : STRING;
END_STRUCT
END_TYPE
```

**Comment by sjelatex** [comment]
After debugging this for a while, I found that the issue found in the class `TwinCAT.Ads.TypeSystem.ReferenceInstance` specifically in the method `bool IReferenceInstanceAccess.TryGetElement(IList<int[]>, out ISymbol)`, after the method has called `IArrayInstance.TryGetElement(IList<int[]>, out ISymbol)`, it will try to cast the output symbol to an `IArrayInstance`, which I believe it shouldn't do. The elements of an array is not necessarily arrays.

It seems like this works in version 6.1.x beacuse that cast is not there.

Worth noting, is that this cast also happens after `IReferenceInstanceAccess.TryGetElement(IList<int[]>, out ISymbol)`, but I haven't figured if this is the expected behaviour.

**Comment by RalfHeitmann** [comment]
sjelatex, thanks for reporting this.
We have released a new Version 4.4.40 that contains a fix.

https://www.nuget.org/packages/Beckhoff.TwinCAT.Ads/4.4.40

Regards

**Comment by sjelatex** [comment]
I have tested this with the same code above with the 4.4.40 version and it still throws the same exception with the same stack trace. This time I cannot see where the cast comes from. Can you confirm if it works for you?

`Unable to cast object of type 'TwinCAT.Ads.TypeSystem.StructInstance' to type 'TwinCAT.TypeSystem.IArrayInstance'.`
```
   at TwinCAT.Ads.TypeSystem.ReferenceInstance.TwinCAT.TypeSystem.IReferenceInstanceAccess.TryGetElement(IList`1 jaggedIndices, ISymbol& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetSubItem(IInstanceCollection`1 coll, String[] pathSplit, Int32 splitIndex, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetSubItem(IInstanceCollection`1 coll, String[] pathSplit, Int32 splitIndex, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetInstanceHierarchically(String instancePath, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.TryGetInstance(String instanceSpecifier, T& symbol)
   at TwinCAT.TypeSystem.Generic.InstanceCollection`1.get_Item(String instanceSpecifier)
   at TwinCAT.TypeSystem.Generic.ReadOnlyInstanceCollection`1.get_Item(String instancePath)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\user\source\repos\ConsoleApp13\ConsoleApp13\Program.cs:line 33
```

**Comment by RalfHeitmann** [comment]
Could you double check that the 4.4.40 is loaded in your Application? E.g. in Visual Studio with Menu->Debug->Modules. Sometimes  older versions of assemblies are hanging around in bin/obj folders or in the Global Assembly Cache ...

**Comment by RalfHeitmann** [comment]
I just checked it against the Package on Nuget.org. At least your testcode
```csharp
static void Main(string[] args)
        {
            using (TcAdsClient client = new TcAdsClient())
            {
                client.Connect(AmsNetId.Local, 851);
                var loader = SymbolLoaderFactory.Create(client, SymbolLoaderSettings.Default);
                var symbols = loader.Symbols;

                var instancePath = "MAIN.MyArray";
                var symbol = symbols[instancePath];
                var subSymbol = symbol.SubSymbols[0]; // Works

                var instancePath2 = "MAIN.MyArray[1]";
                var symbol2 = symbols[instancePath2]; // Works

                var instancePath3 = "MAIN.RefArray";
                var symbol3 = symbols[instancePath3];
                var subSymbol3 = symbol3.SubSymbols[0]; // Works

                var instancePath4 = "MAIN.RefArray[1]";
                var symbol4 = symbols[instancePath4]; // Throws the exception below
                                                      // System.InvalidCastException: 'Unable to cast object of type 'TwinCAT.Ads.TypeSystem.StructInstance' to type 'TwinCAT.TypeSystem.IArrayInstance'.'
            }
        }
```
runs without exception. Seems to be ok.

**Comment by sjelatex** [comment]
It looks like Visual Studio loads the package from GAC_MSIL and when decompiling that file I see the version is
```csharp
[assembly: AssemblyVersion("4.4.0.0")]
[assembly: AssemblyFileVersion("4.4.0.0")]
[assembly: AssemblyInformationalVersion("4.4.0")]
```
Which is not the version I installed from NuGet. I have tried with the latest version of VS 2022 and VS 2019. So the problem appears to be on my site.
<img width="1875" alt="Image" src="https://github.com/user-attachments/assets/bdeb5424-9897-4207-af5c-4853acf88bce" />

**Comment by RalfHeitmann** [comment]
There should never be a 4.4 Version of ADS in the GAC! Unfortunately and accidently, there are older TwinCAT (Sub) installations that do this mistake/have this bug. Beckhoff tools and Components should always use Version 4.3 and only that Version should be in the GAC!

Options you have:
Simply remove that 4.4 Version from the GAC (Backup that file). From now on your own build applications should pick up the right Nuget Package version.
In case you experience Problems with specific TwinCAT components which fail because of missing TwinCAT.Ads.dll, you could add the newest Version 4.4 in the GAC again to fix that, with the drawback that you have to remember to exchange the GAC Version every time you update the Nuget package.

Sorry for the inconvenience and hope that helps.

**Comment by sjelatex** [comment]
I deleted the file and it appears to have solved my issue and I can confirm the 4.4.40 fixes the exception.
